sudo: false
language: go
go:
  - 1.7.x
  - 1.8.x
  - master
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: master
  fast_finish: true
script:
  - go get -t -v ./...
  - go run _example/main.go
  - go run _example/main.go -h
